version: '3.7'

services:
    registry:
        container_name: registry
        image: registry:2.7
        ports:
            - 5000:5000
        volumes:
            - /mnt/nfs:/var/lib/registry
        networks:
            - regisnet            
    registry-ui:
        container_name: registry-ui
        image: joxit/docker-registry-ui:static
        ports:
            - 80:80
        environment:
            - REGISTRY_URL=http://localhost:5000
            - DELETE_IMAGES=true
        networks:
            - regisnet
networks:
    regisnet: